{
 "title": "Nethermind",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "group", "query": "label_values(nethermind_group)" },
   {
    "name": "enode",
    "query": "label_values({nethermind_group=\"$group\"}, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Sync Peers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nethermind_sync_peers{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
    }
   ]
  },
  {
   "title": "Block Number",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "nethermind_blocks{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
    }
   ]
  },
  { "title": "Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Blocks (per second)",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_blocks{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Version",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_version{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}/10"
    }
   ]
  },
  {
   "title": "GC (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(dotnet_collection_count_total{generation=\"0\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Gen 0"
    },
    {
     "expr": "rate(dotnet_collection_count_total{generation=\"1\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Gen 1"
    },
    {
     "expr": "rate(dotnet_collection_count_total{generation=\"2\",job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Gen 2"
    }
   ]
  },
  {
   "title": "Sync Peers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short", "label": "Sync Peers" }
   ],
   "targets": [
    {
     "expr": "nethermind_sync_peers{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Sync Peers"
    }
   ]
  },
  {
   "title": "Blocks DB (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_blocks_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_blocks_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Managed Memory"
    },
    {
     "expr": " process_working_set_bytes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"} - dotnet_total_memory_bytes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Unmanaged Memory"
    }
   ]
  },
  {
   "title": "JSON RPC (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_json_rpc_successes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "RPC Successes"
    },
    {
     "expr": "rate(nethermind_json_rpc_errors{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "RPC Errors"
    },
    {
     "expr": "rate(nethermind_json_rpc_request_deserialization_failures{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Deserialization Failures"
    },
    {
     "expr": "rate(nethermind_json_rpc_invalid_requests{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Invalid Requests"
    }
   ]
  },
  {
   "title": "Fast Blocks",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_fast_headers{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Headers"
    },
    {
     "expr": "nethermind_fast_bodies{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Bodies"
    },
    {
     "expr": "nethermind_fast_receipts{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Receipts"
    }
   ]
  },
  {
   "title": "State Synced (in bytes)",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "nethermind_state_synced{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "State"
    },
    {
     "expr": "rate(nethermind_state_synced{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[60m])*3600"
    }
   ]
  },
  {
   "title": "Beamed Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_beamed_transactions{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Beamed Blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_beamed_blocks{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Blocks"
    }
   ]
  },
  {
   "title": "Beamed Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_beamed_requests{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Beamed Trie Nodes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_beamed_trie_nodes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Trie Nodes"
    }
   ]
  },
  {
   "title": "Uptime (track restarts)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "process_cpu_seconds_total{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "Memory Growth (per second)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "deriv(dotnet_total_memory_bytes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m]) > 0",
     "legendFormat": "Managed Memory",
     "target": "*.Nethermind_Runner.*.*.*.*.gauge.*.Process_Physical_Memory"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Connections (per minute)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 92 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_incoming_connections{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Incoming Connections"
    },
    {
     "expr": "rate(nethermind_outgoing_connections{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Outgoing Connections"
    },
    {
     "expr": "rate(nethermind_handshakes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Handshakes"
    },
    {
     "expr": "rate(nethermind_hellos_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Hellos Sent"
    },
    {
     "expr": "rate(nethermind_hellos_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Hellos Received"
    },
    {
     "expr": "rate(nethermind_statuses_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Statuses Sent"
    },
    {
     "expr": "rate(nethermind_statuses_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Statuses Received"
    }
   ]
  },
  {
   "title": "Pending Txs (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_pending_transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Received"
    },
    {
     "expr": "rate(nethermind_pending_transactions_discarded{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Discarded"
    },
    {
     "expr": "rate(nethermind_pending_transactions_known{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Already Known"
    },
    {
     "expr": "rate(nethermind_pending_transactions_sent{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Sent"
    },
    {
     "expr": "rate(nethermind_pending_txs_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "DB Reads"
    },
    {
     "expr": "rate(nethermind_pending_txs_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "DB Writes"
    }
   ]
  },
  {
   "title": "Disconnects (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_too_many_peers_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Too Many Peers"
    },
    {
     "expr": "rate(nethermind_client_quitting_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Client Quitting"
    },
    {
     "expr": "rate(nethermind_receive_message_timeout_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Receive Timeouts"
    },
    {
     "expr": "rate(nethermind_already_connected_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Already Connected"
    },
    {
     "expr": "rate(nethermind_breach_of_protocol_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Breach of Protocol"
    },
    {
     "expr": "rate(nethermind_incompatible_p2pdisconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Incompatible P2P"
    },
    {
     "expr": "rate(nethermind_null_node_identity_disconnects{job=\"nethermind\",_instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Null Identity"
    },
    {
     "expr": "rate(nethermind_unexpected_identity_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Unexpected Identity"
    },
    {
     "expr": "rate(nethermind_useless_peer_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Useless Peer"
    },
    {
     "expr": "rate(nethermind_diconnect_requested_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Requested"
    },
    {
     "expr": "rate(nethermind_tcp_subsystem_error_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "TCP Error"
    },
    {
     "expr": "rate(nethermind_same_as_self_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Same as Self"
    },
    {
     "expr": "rate(nethermind_other_disconnects{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Eth62, Eth63 (per minute)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_eth62get_block_headers_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "GetBlockHeaders"
    },
    {
     "expr": "rate(nethermind_eth62block_headers_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "BlockHeaders"
    },
    {
     "expr": "rate(nethermind_eth62get_block_bodies_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "GetBlockBodies"
    },
    {
     "expr": "rate(nethermind_eth62block_bodies_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "BlockBodies"
    },
    {
     "expr": "rate(nethermind_eth62transactions_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Transactions"
    },
    {
     "expr": "rate(nethermind_eth62new_block_hashes_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "NewBlockHashes"
    },
    {
     "expr": "rate(nethermind_eth62new_block_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "NewBlock"
    },
    {
     "expr": "rate(nethermind_eth63get_node_data_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "GetNodeData"
    },
    {
     "expr": "rate(nethermind_eth63get_receipts_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "GetReceipts"
    },
    {
     "expr": "rate(nethermind_eth63node_data_received{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "NodeData"
    }
   ]
  },
  {
   "title": "Blocks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nethermind_blocks{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}"
    }
   ]
  },
  { "title": "Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 128 } },
  {
   "title": "Receipts DB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 129 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_receipts_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[10s])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_receipts_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[10s])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Code DB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 135 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_code_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_code_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "State Tree",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 141 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_state_tree_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_state_tree_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Block Info DB",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 147 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_block_infos_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_block_infos_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "State DB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 153 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_state_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_state_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Storage Tree",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_storage_tree_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_storage_tree_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Trie Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 168 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_tree_node_rlp_decodings{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "RLP.Encode"
    },
    {
     "expr": "rate(nethermind_tree_node_rlp_encodings{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "RLP.Decode"
    },
    {
     "expr": "rate(nethermind_tree_node_hash_calculations{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[1m])*60",
     "legendFormat": "Keccak"
    }
   ]
  },
  {
   "title": "Other DB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 175 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(nethermind_other_db_reads{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[10s])",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(nethermind_other_db_writes{job=\"nethermind\",instance=\"$enode\",nethermind_group=\"$group\"}[10s])",
     "legendFormat": "Writes"
    }
   ]
  }
 ]
}